import { ReactorArchitecture } from "@/types/nuclear";

export const REACTOR_ARCHITECTURES: ReactorArchitecture[] = [
  {
    id: "smr-light-water",
    name: "Small Modular Light Water (SMR)",
    category: "SMR (Light Water)",
    status: "Commercial / Near-Deployment",
    thermalOutputMWth: 250,
    electricOutputMWe: 77,
    efficiencyPercent: 31,
    fuelType: "Standard <5% Enriched UO₂ Ceramic Pellets",
    coolant: "Natural Light Water (H₂O)",
    operatingTempC: 300,
    deploymentFootprintAcres: 35,
    safetyParadigm: "Triple-Fail-Safe Gravity Driven (Walk-Away Passive)",
    passiveSafetyMechanisms: [
      {
        title: "Underground Heat Sink Pool",
        description: "Entire reactor module is submerged in a subterranean water pool capable of absorbing residual decay heat indefinitely without operator intervention or electric pumps.",
        physicsLaw: "Natural convection, buoyancy-driven fluid thermodynamics, and passive atmospheric condensation.",
      },
      {
        title: "Gravity-Actuated Containment Valves",
        description: "In any power loss event, fail-safe magnetic containment valves de-energize and open under gravity, flooding the reactor vessel with cooling water.",
        physicsLaw: "Gravitational force & electromagnetic de-energization.",
      },
      {
        title: "Integral Steam Generator Architecture",
        description: "Eliminates large external primary coolant pipes, removing the physical possibility of a large-break Loss of Coolant Accident (LOCA).",
        physicsLaw: "Integrated pressure boundary mechanics.",
      },
    ],
    keyAdvantages: [
      "Factory prefabricated and transported by rail/barge, slashing capital cost and construction risk.",
      "Scalable multi-module configuration (1 to 12 modules per facility).",
      "Direct drop-in replacement for retired coal-fired thermal generation plants utilizing existing transmission lines.",
      "Zero reliance on AC/DC external power for safety shutdown.",
    ],
    industrialUseCases: [
      "24/7 AI Datacenter clusters (100-500 MW)",
      "Municipal district heating",
      "Island & remote industrial microgrids",
      "Seawater reverse-osmosis desalination",
    ],
    commercialLeaders: ["NuScale Power (VOYGR)", "GE Hitachi (BWRX-300)", "Rolls-Royce SMR", "Westinghouse AP300"],
    schematicDetails: {
      coreType: "Compact Pressurized Water Core",
      containmentBarrier: "High-Strength Steel Vacuum Pressure Vessel",
      refuelingIntervalMonths: 24,
      decayHeatRemovalTimeDays: "Indefinite (Passive Convection)",
    },
  },
  {
    id: "gen4-htgr",
    name: "High-Temperature Gas-Cooled (HTGR)",
    category: "Gen IV High-Temp Gas",
    status: "Licensed Construction",
    thermalOutputMWth: 200,
    electricOutputMWe: 80,
    efficiencyPercent: 40,
    fuelType: "TRISO (Tristructural-Isotropic) Meltdown-Proof Fuel Pebbles",
    coolant: "Inert High-Pressure Helium Gas",
    operatingTempC: 750,
    deploymentFootprintAcres: 20,
    safetyParadigm: "Inherent Physics Meltdown Immunity (TRISO Containment)",
    passiveSafetyMechanisms: [
      {
        title: "TRISO Ceramic Micro-Encapsulation",
        description: "Each microscopic uranium oxycarbide kernel is wrapped in carbon and silicon carbide layers that withstand temperatures exceeding 1,600°C—far above any possible operating accident state.",
        physicsLaw: "Refractory silicon carbide thermodynamic stability and fission product retention.",
      },
      {
        title: "Strong Negative Temperature Coefficient",
        description: "As core temperature climbs, Doppler neutron resonance absorption instantly quenches the fission chain reaction, naturally throttling power without control rods.",
        physicsLaw: "Doppler resonance broadening physics (Nuclear cross-section kinematics).",
      },
      {
        title: "Inert Single-Phase Helium Coolant",
        description: "Helium gas does not become radioactive, cannot boil or cavitate, and produces zero corrosive chemical reactions with reactor core structures.",
        physicsLaw: "Noble gas non-reactive chemical inertness.",
      },
    ],
    keyAdvantages: [
      "Delivers high-grade industrial process heat (750°C - 950°C) for green hydrogen and synthetic fuel production.",
      "Cannot physically experience a core meltdown under complete loss of coolant and control systems.",
      "Operates on continuous on-line pebble refueling without plant downtime.",
      "High thermodynamic cycle efficiency (>40%) utilizing direct Brayton gas turbines.",
    ],
    industrialUseCases: [
      "Zero-carbon green hydrogen production via sulfur-iodine / high-temp steam electrolysis",
      "Petrochemical & chemical manufacturing feedstock heat",
      "Steel and cement decarbonization",
      "Synthetic aviation fuel synthesis",
    ],
    commercialLeaders: ["X-energy (Xe-100 / Dow Chemical)", "Kairos Power (Hermes / Google PPA)", "Ultra Safe Nuclear (Micro-Modular)"],
    schematicDetails: {
      coreType: "Pebble Bed / Prismatic Block Core",
      containmentBarrier: "Multilayer Silicon Carbide Micro-Vessels + Concrete Bunker",
      refuelingIntervalMonths: 0, // Continuous on-line refueling
      decayHeatRemovalTimeDays: "Unlimited (Passive Radiant & Convective Air Heat Sink)",
    },
  },
  {
    id: "gen4-sodium-fast",
    name: "Sodium-Cooled Fast Breeder Reactor (SFR)",
    category: "Gen IV Sodium Fast",
    status: "Advanced Demo",
    thermalOutputMWth: 840,
    electricOutputMWe: 345,
    efficiencyPercent: 41,
    fuelType: "HALEU Metallic Uranium-Zirconium Alloy (Waste Recyclable)",
    coolant: "Liquid Sodium Metal (Atmospheric Pressure)",
    operatingTempC: 500,
    deploymentFootprintAcres: 45,
    safetyParadigm: "Gigawatt-Scale Molten Salt Energy Storage Buffer",
    passiveSafetyMechanisms: [
      {
        title: "Low-Pressure Liquid Metal Coolant",
        description: "Liquid sodium operates at standard atmospheric pressure with a boiling point of 883°C. Zero high-pressure explosive expulsion risk.",
        physicsLaw: "Liquid metal high thermal conductivity and wide liquid phase margin.",
      },
      {
        title: "Gigawatt-Scale Molten Salt Thermal Reservoir",
        description: "Pairs with a gigawatt-hour molten salt thermal storage tank, enabling base 345 MWe nuclear output to surge to 500 MWe peak output for 5.5 hours to stabilize renewable swings.",
        physicsLaw: "High sensible heat capacity of nitrate salts.",
      },
      {
        title: "Spent Fuel Actino-Fission Recycling",
        description: "Fast neutrons can fission transuranic actinides, reducing the radioactive longevity of high-level nuclear waste from 300,000 years to less than 300 years.",
        physicsLaw: "Fast-spectrum neutron capture cross-sections.",
      },
    ],
    keyAdvantages: [
      "Extracts up to 60x-100x more energy from uranium reserves compared to conventional thermal reactors.",
      "Can utilize existing stockpiles of depleted uranium and spent fuel as feedstocks.",
      "Flexible load-following capabilities that harmonize seamlessly with variable wind/solar grids.",
      "High thermal conductivity simplifies heat exchange loops.",
    ],
    industrialUseCases: [
      "Gigawatt-scale flexible grid stabilization",
      "Repurposing legacy nuclear waste into clean electricity",
      "Heavy industrial metallurgical plants",
      "High-power regional grid hubs",
    ],
    commercialLeaders: ["TerraPower (Natrium / Bill Gates)", "GE Vernova (PRISM)", "OKBM Afrikantov (BN-800)"],
    schematicDetails: {
      coreType: "Fast Neutron Pool-Type Sodium Core",
      containmentBarrier: "Double-Walled Austenitic Stainless Steel Tank",
      refuelingIntervalMonths: 36,
      decayHeatRemovalTimeDays: "Passive Reactor Vessel Auxiliary Cooling System (RVACS)",
    },
  },
  {
    id: "fusion-tokamak",
    name: "High-Field Magnetic Confinement Fusion",
    category: "Next-Gen Fusion",
    status: "Active Pilot R&D",
    thermalOutputMWth: 140,
    electricOutputMWe: 50,
    efficiencyPercent: 36,
    fuelType: "Deuterium (from seawater) + Tritium (lithium blanket breeding)",
    coolant: "Helium / Supercritical CO₂ Loop",
    operatingTempC: 150000000, // 150M °C plasma core
    deploymentFootprintAcres: 15,
    safetyParadigm: "Zero Chain Reaction Physics (Self-Extinguishing Plasma)",
    passiveSafetyMechanisms: [
      {
        title: "Plasma Disruption Self-Extinction",
        description: "Fusion requires precise magnetic confinement and temperature conditions. Any anomaly or breach causes the plasma to immediately cool and stop within microseconds.",
        physicsLaw: "Lawson criterion plasma confinement loss.",
      },
      {
        title: "Gram-Scale Core Fuel Inventory",
        description: "The entire reactor core contains less than 5 grams of fuel at any given moment, preventing any catastrophic runaway energy release.",
        physicsLaw: "Ultra-low fuel inventory density physics.",
      },
      {
        title: "Zero Long-Lived Transuranic Waste",
        description: "Fusion yields non-toxic helium ash. Structural activation isotopes decay safely to ambient background levels within a few decades.",
        physicsLaw: "Deuterium-Tritium nuclear reaction kinematics (D + T → ⁴He + n + 17.6 MeV).",
      },
    ],
    keyAdvantages: [
      "Inexhaustible fuel supply extracted from ocean water and abundant lithium crust.",
      "Absolute zero risk of meltdown, runaway criticality, or weapon proliferation.",
      "High-temperature superconducting (HTS) REBCO magnets enabling compact commercial footprints.",
      "Highest theoretical energy density in the known physical universe.",
    ],
    industrialUseCases: [
      "Infinite clean baseload power for planetary civilizations",
      "Deep space propulsion and extraterrestrial habitats",
      "Direct carbon-air capture at gigaton scale",
      "Complete global grid decarbonization",
    ],
    commercialLeaders: ["Commonwealth Fusion Systems (SPARC)", "Tokamak Energy (ST40)", "Helion Energy", "ITER Consortium"],
    schematicDetails: {
      coreType: "Compact High-Field Superconducting Tokamak / Spherical Torus",
      containmentBarrier: "Cryogenic Vacuum Cryostat + High-Density Radiation Shielding",
      refuelingIntervalMonths: 12,
      decayHeatRemovalTimeDays: "Immediate Ambient Radiation Decay (<1 Hour)",
    },
  },
];
